// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU7goXcYkGOS8eMiRtJ_oiWUzo9VT6xRU',
    appId: '1:138837610266:web:81eb96ff947f98d3fa26a3',
    messagingSenderId: '138837610266',
    projectId: 'new-flutter-app-c5fdb',
    authDomain: 'new-flutter-app-c5fdb.firebaseapp.com',
    storageBucket: 'new-flutter-app-c5fdb.appspot.com',
    measurementId: 'G-9PPERHVYZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnmCLpbyHOSV97wnNM7s4C3OVQU3VnEhA',
    appId: '1:138837610266:android:461a6f411279e161fa26a3',
    messagingSenderId: '138837610266',
    projectId: 'new-flutter-app-c5fdb',
    storageBucket: 'new-flutter-app-c5fdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpm-AT4R89Kd5PoBipaKaLCUY7qmcFEt0',
    appId: '1:138837610266:ios:4ce06a6536ad66fcfa26a3',
    messagingSenderId: '138837610266',
    projectId: 'new-flutter-app-c5fdb',
    storageBucket: 'new-flutter-app-c5fdb.appspot.com',
    iosClientId: '138837610266-lghr48phfr8qbpa7il924lv9mg9iu040.apps.googleusercontent.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpm-AT4R89Kd5PoBipaKaLCUY7qmcFEt0',
    appId: '1:138837610266:ios:0218003d290f795cfa26a3',
    messagingSenderId: '138837610266',
    projectId: 'new-flutter-app-c5fdb',
    storageBucket: 'new-flutter-app-c5fdb.appspot.com',
    iosClientId: '138837610266-6i8auub8mr7m82btefsprq7jcsaig7qa.apps.googleusercontent.com',
    iosBundleId: 'com.example.newApp.RunnerTests',
  );
}
